//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsAccumulator.cpp
//  @ Date : 1/29/2009
//  @ Author : 
//
//


#include "WsAccumulator.h"
#include "WsSc.h"
#include "WsDashboard.h"

WsAccumulator::WsAccumulator(WsSc* p_sc)
{
    ap_sc = p_sc;
    a_accumSpeedIn  =  1;
    a_accumSpeedOut = -1;

    ap_dashboard = WsDashboard::getInstance();
}

WsAccumulator::~WsAccumulator()
{
}

float WsAccumulator::setState(WsAccumulatorStateT state)
{
    float speed = 0;

    switch(state)
    {
        case ACCUM_STATE_OFF:
            speed = 0;
            break;
        case ACCUM_STATE_IN:
            speed = a_accumSpeedIn;
            break;
        case ACCUM_STATE_OUT:
            speed = a_accumSpeedOut;
            break;
        default:
            speed = 0;
            break;
    }

    if(ap_sc != NULL)
    {
        ap_sc->Set(speed);
    }
    ap_dashboard->setValue(IDX_OUT_ACCUM, speed);
    return speed;
}

