//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsAppendageControl.h
//  @ Date : 1/31/2009
//  @ Author : 
//
//


#if !defined(_WSAPPENDAGECONTROL_H)
#define _WSAPPENDAGECONTROL_H

#include <stdio.h>
#include "WsShooter.h"
#include "WsAccumulator.h"
#include "WsElevator.h"

class WsControllerPolarStick;
class WsControllerButton;
class WsDashboard;


class WsAppendageControl
{
public:
    WsAppendageControl();
    WsAccumulator::WsAccumulatorStateT getAccumulatorCommand(void);
    void getEscalatorSpeeds(float* frontSpeed, float* backSpeed);
    WsElevator::WsElevatorStateT getLeftElevatorCommand(void );
    WsElevator::WsElevatorStateT getRightElevatorCommand(void );
    WsShooter::WsShooterStateT getShooterCommand(void);
    void assignElevatorStick(WsControllerPolarStick* p_stick);
    void assignElevatorDisableButton(WsControllerButton* p_button);
    void assignEscalatorStick(WsControllerPolarStick* p_stick);
    void assignAccumulatorButtons(WsControllerButton* p_in, WsControllerButton* p_out);
    void assignShooterButtons(WsControllerButton* p_in, WsControllerButton* p_outFast, WsControllerButton* p_outSlow);
    void assignAccumLoadButton(WsControllerButton* p_button);
    void assignRaiseShootLeftButton(WsControllerButton* p_button);
    void assignRaiseShootBothButton(WsControllerButton* p_button);
    void assignRaiseShootRightButton(WsControllerButton* p_button);
    void assignDownOutButton(WsControllerButton* p_button);

protected:
    WsControllerPolarStick* ap_elevatorStick;
    WsControllerButton* ap_elevatorDisableButton;
    WsControllerPolarStick* ap_escalatorStick;
    WsControllerButton* ap_shootOutFastButton;
    WsControllerButton* ap_shootOutSlowButton;
    WsControllerButton* ap_shootInButton;
    WsControllerButton* ap_accumInButton;
    WsControllerButton* ap_accumOutButton;
    WsControllerButton* ap_accumLoadButton;
    WsControllerButton* ap_raiseShootLeftButton;
    WsControllerButton* ap_raiseShootBothButton;
    WsControllerButton* ap_raiseShootRightButton;
    WsControllerButton* ap_downOutButton;
    float a_escLoadSpeed;

    WsDashboard* ap_dashboard;
};

#endif  //_WSAPPENDAGECONTROL_H
