//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsAttack3Joystick.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSATTACK3JOYSTICK_H)
#define _WSATTACK3JOYSTICK_H

#include <stdio.h>
#include "WsRegularJoystick.h"

class WsAttack3Joystick : public WsRegularJoystick
{
};

#endif  //_WSATTACK3JOYSTICK_H
