//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoOutpostOutpostStraight.h
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#if !defined(_WSAUTOOUTPOSTOUTPOSTSTRAIGHT_H)
#define _WSAUTOOUTPOSTOUTPOSTSTRAIGHT_H

#include <stdio.h>
#include "WsAutoNStepBase.h"

class WsAutoOutpostOutpostStraight : public WsAutoNStepBase
{
public:
    WsAutoOutpostOutpostStraight();
    virtual ~WsAutoOutpostOutpostStraight();
    virtual void initParams(void);
};

#endif  //_WSAUTOOUTPOSTOUTPOSTSTRAIGHT_H
