//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoOutpostOutpostLeft.h
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#if !defined(_WSAUTOOUTPOSTOUTPOSTLEFT_H)
#define _WSAUTOOUTPOSTOUTPOSTLEFT_H

#include <stdio.h>
#include "WsAutoNStepBase.h"

class WsAutoOutpostOutpostLeft : public WsAutoNStepBase
{
public:
    WsAutoOutpostOutpostLeft();
    virtual ~WsAutoOutpostOutpostLeft();
    virtual void initParams(void);
};

#endif  //_WSAUTOOUTPOSTOUTPOSTLEFT_H
