//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoThreeStepBase.h
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#if !defined(_WSAUTOTHREESTEPBASE_H)
#define _WSAUTOTHREESTEPBASE_H

#include <stdio.h>
#include "WsAutoProgramBase.h"

#include "WsAccumulator.h"
#include "WsEscalator.h"
#include "WsElevator.h"
#include "WsShooter.h"
#include "WsDriveVector.h"

class Timer;
class Dashboard;

class WsAutoThreeStepBase : public WsAutoProgramBase
{
public:

    typedef enum
    {
        AUTO_STATE_INIT,
        AUTO_STATE_INIT_DELAY,
        AUTO_STATE_DRIVE1,
        AUTO_STATE_COAST1,
        AUTO_STATE_DRIVE2,
        AUTO_STATE_COAST2,
        AUTO_STATE_DRIVE3,
        AUTO_STATE_COAST3,
        AUTO_STATE_DONE
    } WsAutoThreeStepStateT;

    WsAutoThreeStepBase();
    virtual ~WsAutoThreeStepBase();
    virtual bool run(void );
    virtual void initParams(void);
protected:
    WsAutoThreeStepStateT a_progState;

    // Attributes for init
    WsAccumulator::WsAccumulatorStateT a_initAccumState;
    float a_initEscFrontSpeed;
    float a_initEscBackSpeed;
    WsShooter::WsShooterStateT a_initShooterState;
    WsElevator::WsElevatorStateT a_initElevLeftState;
    WsElevator::WsElevatorStateT a_initElevRightState;

    // Attributes for init delay
    double a_initDelay;

    // Attributes for drive 1
    float a_drive1CrabAngle;
    WsDriveVector a_drive1Vector;
    double a_drive1Timeout;

    // Attributes for coast 1
    float a_coast1CrabAngle;
    double a_coast1Timeout;

    // Attributes for drive 2
    float a_drive2CrabAngle;
    WsDriveVector a_drive2Vector;
    double a_drive2Timeout;

    // Attributes for coast 2
    float a_coast2CrabAngle;
    double a_coast2Timeout;

    // Attributes for drive 3
    float a_drive3CrabAngle;
    WsDriveVector a_drive3Vector;
    double a_drive3Timeout;

    // Attributes for coast 3
    float a_coast3CrabAngle;
    double a_coast3Timeout;

    // Attributes for done
    float a_doneCrabAngle;
    WsAccumulator::WsAccumulatorStateT a_doneAccumState;
    float a_doneEscFrontSpeed;
    float a_doneEscBackSpeed;
    WsShooter::WsShooterStateT a_doneShooterState;
    WsElevator::WsElevatorStateT a_doneElevLeftState;
    WsElevator::WsElevatorStateT a_doneElevRightState;
};

#endif  //_WSAUTOTHREESTEPBASE_H
