//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoSleeper.cpp
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#include "WsAutoSleeper.h"
#include "WsDashboard.h"

WsAutoSleeper::WsAutoSleeper()
{
    ap_dashboard = WsDashboard::getInstance();

}

WsAutoSleeper::~WsAutoSleeper()
{

}

void WsAutoSleeper::initParams(void)
{
}

bool WsAutoSleeper::run(void )
{
    static float counter = 0;

    printf("SLEEP\n");

    turnOffDriveBase();
    turnOffAppendages();

    ap_dashboard->setValue(IDX_AUTO_DATA1, counter++);

    return true;
}

