//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoSleeper.h
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#if !defined(_WSAUTOSLEEPER_H)
#define _WSAUTOSLEEPER_H

#include <stdio.h>
#include "WsAutoProgramBase.h"

class WsAutoSleeper : public WsAutoProgramBase
{
public:
    WsAutoSleeper();
    virtual ~WsAutoSleeper();
    virtual bool run(void );
    virtual void initParams(void);
};

#endif  //_WSAUTOSLEEPER_H
