//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoOutpostOutpostRight.h
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#if !defined(_WSAUTOOUTPOSTOUTPOSTRIGHT_H)
#define _WSAUTOOUTPOSTOUTPOSTRIGHT_H

#include <stdio.h>
#include "WsAutoNStepBase.h"

class WsAutoOutpostOutpostRight : public WsAutoNStepBase
{
public:
    WsAutoOutpostOutpostRight();
    virtual ~WsAutoOutpostOutpostRight();
    virtual void initParams(void);
};

#endif  //_WSAUTOOUTPOSTOUTPOSTRIGHT_H
