//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoOutpostOutpostStraight.cpp
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#include "WsAutoOutpostOutpostStraight.h"

WsAutoOutpostOutpostStraight::WsAutoOutpostOutpostStraight()
{
}

WsAutoOutpostOutpostStraight::~WsAutoOutpostOutpostStraight()
{
}

void WsAutoOutpostOutpostStraight::initParams(void)
{
    WsAutoNStepBase::WsAutoNStepCmdT drive1;
    WsAutoNStepBase::WsAutoNStepCmdT drive2;
    WsAutoNStepBase::WsAutoNStepCmdT drive3;

    WsAutoNStepBase::initParams();

    // Attributes for drive 1
    drive1.crabAngle = 0;
    drive1.driveVector.a_speed = .2;
    drive1.driveVector.a_direction = 0;
    drive1.timeout = .2;

    // Attributes for drive 2
    drive2.crabAngle = 0;
    drive2.driveVector.a_speed = .75;
    drive2.driveVector.a_direction = 0;
    drive2.timeout = 3;

    // Attributes for drive 3
    drive3.crabAngle = 0;
    drive3.driveVector.a_speed = .3;
    drive3.driveVector.a_direction = 0;
    drive3.timeout = .25;

    // Add the steps to the program...order matters
    addStep(drive1);
    addStep(drive2);
    addStep(drive3);
}

