//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsCalibration.h
//  @ Date : 1/19/2009
//  @ Author : 
//
//


#if !defined(_WSCALIBRATION_H)
#define _WSCALIBRATION_H

#include <stdio.h>

#define CALIBRATION_FILENAME "/ws_calib"
#define PROTO_FILENAME "/ws_proto"

class WsCalibration
{
public:
    typedef enum
    {
      CRAB_MID = 0,
      CRAB_LEFT,
      CRAB_RIGHT,
      ENCODER_FL,
      ENCODER_FR,
      ENCODER_BL,
      ENCODER_BR,

      /* do not change the line below */
      MAX_NUM_VALUES,
    } CalibrationIndexT;

    virtual ~WsCalibration();
    static WsCalibration* getInstance();
    void saveData();
    void readData();
    void printValues();
    bool isCompetitionRobot(void );
    UINT32 getValue(CalibrationIndexT index);
    void setValue(CalibrationIndexT index, UINT32 value);

protected:
    WsCalibration();

    UINT32 a_data[MAX_NUM_VALUES];
    bool a_competitionRobot;

private:
    static WsCalibration* ap_instance;
};

#endif  //_WSCALIBRATION_H
