//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerStickyButton.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERSTICKYBUTTON_H)
#define _WSCONTROLLERSTICKYBUTTON_H

#include <stdio.h>
#include "WsControllerButton.h"

class Joystick;
class Gamepad;

class WsControllerStickyButton : public WsControllerButton
{
public:
    WsControllerStickyButton(Joystick* p_js, UINT32 button);
    WsControllerStickyButton(Gamepad* p_pad, UINT32 button);
    virtual ~WsControllerStickyButton();
    virtual bool getState(void );
    virtual void resetState(void);
protected:
    bool a_statePrev;
    bool a_stickyState;
};

#endif  //_WSCONTROLLERSTICKYBUTTON_H
