//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerAxis.cpp
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#include "WsControllerAxis.h"
#include "Joystick.h"
#include "Gamepad.h"

WsControllerAxis::WsControllerAxis(Joystick* p_js, UINT32 axis)
{
    /* Store the joystick and axis for later use */
    ap_joystick = p_js;
    ap_gamepad = NULL;
    ap_ds = NULL;
    a_axisNum = axis;
    a_channelNum = 0;
    a_invert = false;
}

WsControllerAxis::WsControllerAxis(Gamepad* p_pad, UINT32 axis)
{
    /* Store the gamepad and axis for later use */
    ap_joystick = NULL;
    ap_gamepad = p_pad;
    ap_ds = NULL;
    a_axisNum = axis;
    a_channelNum = 0;
    a_invert = false;
}

WsControllerAxis::~WsControllerAxis()
{
}

float WsControllerAxis::getValue(void )
{
    float value = 0;

    if(ap_joystick != NULL)
    {
        value = ap_joystick->GetRawAxis(a_axisNum);
    }
    else if(ap_gamepad != NULL)
    {
        value = ap_gamepad->GetRawAxis(a_axisNum);
    }

    value = applyInvert(value);

    return value;
}

float WsControllerAxis::applyInvert(float value)
{
    if(a_invert == true)
    {
        return value * -1;
    }
    else
    {
        return value;
    }
}
