//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerAnalogButton.cpp
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#include "WsControllerAnalogButton.h"
#include "Joystick.h"

WsControllerAnalogButton::WsControllerAnalogButton(Joystick* p_js, UINT32 axis, float thresh, bool aboveOn) :
                          WsControllerButton(p_js, 0)
{
    a_threshold = thresh;
    a_aboveOn = aboveOn;
    a_axisNum = axis;
}

WsControllerAnalogButton::~WsControllerAnalogButton()
{
}

bool WsControllerAnalogButton::getState(void )
{
    float value = 0;
    bool state = false;

    if(ap_joystick != NULL)
    {
        value = ap_joystick->GetRawAxis(a_axisNum);
    }

    if(value > a_threshold)
    {
        state = a_aboveOn;
    }
    else
    {
        state = !a_aboveOn;
    }

    return state;
}

