//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControlMethodBase.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLMETHODBASE_H)
#define _WSCONTROLMETHODBASE_H

#include <stdio.h>

class WsControlMethodBase
{
};

#endif  //_WSCONTROLMETHODBASE_H
