//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControlMethodArcade.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLMETHODARCADE_H)
#define _WSCONTROLMETHODARCADE_H

#include <stdio.h>
#include "WsControlMethodBase.h"
#include "WsDriveVector.h"
#include "WsControllerPolarStick.h"

class WsControllerAxis;
class WsControllerButton;
class WsDashboard;

class WsControlMethodArcade : public WsControlMethodBase
{
public:
    WsControlMethodArcade();
    virtual ~WsControlMethodArcade();
    void assignDriveStick(WsControllerPolarStick* p_stick);
    void assignTurboButton(WsControllerButton* p_turbo);
    virtual WsDriveVector getDriveVector(void );

    virtual bool getTurboState(void);
    virtual void clearTurboState(void);
protected:
    WsControllerPolarStick* ap_driveStick;
    WsControllerButton* ap_turboButton;
    float a_turboScaleFactor;
    bool a_turboState;


    
    WsDashboard* ap_dashboard;
    
};

#endif  //_WSCONTROLMETHODARCADE_H
