//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerMultiStickyButton.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERMULTISTICKYBUTTON_H)
#define _WSCONTROLLERMULTISTICKYBUTTON_H

#include <stdio.h>
#include "WsControllerButton.h"

class WsControllerMultiStickyButton : public WsControllerButton
{
public:
    WsControllerMultiStickyButton(Joystick* p_js, UINT32 onButton, UINT32 offButton);
    virtual ~WsControllerMultiStickyButton();
    virtual bool getState(void );
protected:
    bool a_stickyState;
    UINT32 a_offButtonNum;
};

#endif  //_WSCONTROLLERMULTISTICKYBUTTON_H
