//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerMultiStickyButton.cpp
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#include "WsControllerMultiStickyButton.h"
#include "Joystick.h"
#include "WsControllerButton.h"

WsControllerMultiStickyButton::WsControllerMultiStickyButton(Joystick* p_js, UINT32 onButton, UINT32 offButton) :
                               WsControllerButton(p_js, onButton)
{
    a_stickyState = false;
    a_offButtonNum = offButton;
}

WsControllerMultiStickyButton::~WsControllerMultiStickyButton()
{
}

bool WsControllerMultiStickyButton::getState(void )
{
    bool offButtonState = false;
    bool onButtonState = false;

    onButtonState = WsControllerButton::getState();

    if(ap_joystick != NULL)
    {
        offButtonState = ap_joystick->GetRawButton(a_offButtonNum);
    }

    if(onButtonState == true)
    {
        a_stickyState = true;
    }
    else if(offButtonState == true)
    {
        a_stickyState = false;
    }

    return a_stickyState;
}

