//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerTransitionButton.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERTRANSITIONBUTTON_H)
#define _WSCONTROLLERTRANSITIONBUTTON_H

#include <stdio.h>
#include "WsControllerButton.h"

class WsControllerTransitionButton : public WsControllerButton
{
};

#endif  //_WSCONTROLLERTRANSITIONBUTTON_H
