//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControlMethodCrab.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLMETHODCRAB_H)
#define _WSCONTROLMETHODCRAB_H

#include <stdio.h>
#include <math.h>
#include "WsControlMethodArcade.h"
#include "WsDriveVector.h"
#include "WsControllerPolarStick.h"

class WsDashboard;

class WsControlMethodCrab : public WsControlMethodArcade
{
public:
    WsControlMethodCrab();
    virtual ~WsControlMethodCrab();
    void assignCrabStick(WsControllerPolarStick* p_stick);
    void assignCrabDisableButton(WsControllerButton* p_disable);
    void assignCrabManualButton(WsControllerButton* p_manual);
    void assignCrabNudgeButtons(WsControllerButton* p_left, WsControllerButton* p_right);
    virtual WsDriveVector getDriveVector(void );
    bool getCrabEnableState(void );
    float getCrabWheelAngle(void );
    float getCrabManualSpeed(void );

    typedef enum
    {
        NUDGE_NONE,
        NUDGE_LEFT,
        NUDGE_RIGHT
    } CrabNudgeStateT;


protected:
    WsControllerPolarStick *ap_crabStick;
    WsControllerButton* ap_crabDisableButton;
    WsControllerButton* ap_crabManualButton;
    WsControllerButton* ap_crabNudgeLeftButton;
    WsControllerButton* ap_crabNudgeRightButton;
    float a_crab_stick_radius_thresh;
    float a_crab_manu_scale;
    float a_crab_nudge_angle;
    
    WsDashboard* ap_dashboard;
};

#endif  //_WSCONTROLMETHODCRAB_H
