//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsControllerPolarStick.h
//  @ Date : 1/17/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERPOLARSTICK_H)
#define _WSCONTROLLERPOLARSTICK_H

#include <stdio.h>
#include <math.h>
#include "WsTrig.h"

//Joystick Bounds.  Currently 1.0f
#define BOUNDS 1.0f

class WsControllerAxis;

class WsControllerPolarStick
{
public:
    WsControllerPolarStick(WsControllerAxis* xAxis, WsControllerAxis* yAxis);
    virtual ~WsControllerPolarStick();
    float getRadius(void);
    float getAngle(void);
    float getX(void);
    float getY(void);
protected:
    float calcRadius(float x, float y);
    float calcAngle(float x, float y);
    WsControllerAxis* ap_xAxis;
    WsControllerAxis* ap_yAxis;
};

#endif  //_WSCONTROLLERPOLARSTICK_H
