//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveBase.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEBASE_H)
#define _WSDRIVEBASE_H

#include <stdio.h>

class WsTractionWheel;

class WsDriveBase
{
protected:
    WsTractionWheel* ap_scLF;
    WsTractionWheel* ap_scLB;
    WsTractionWheel* ap_scRF;
    WsTractionWheel* ap_scRB;
};

#endif  //_WSDRIVEBASE_H
