//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveBaseTank.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEBASETANK_H)
#define _WSDRIVEBASETANK_H

#include <stdio.h>
#include "WsDriveBase.h"

class WsTractionWheel;
class WsDriveVector;
class WsDashboard;

class WsDriveBaseTank : public WsDriveBase
{
public:
    WsDriveBaseTank(WsTractionWheel* p_lf, WsTractionWheel* p_lb,
                    WsTractionWheel* p_rf, WsTractionWheel* p_rb);
    WsDriveBaseTank(WsTractionWheel* p_l, WsTractionWheel* p_r);
    virtual ~WsDriveBaseTank();
    virtual void setVector(WsDriveVector* p_vector);
    virtual void calcTankOutput(WsDriveVector* p_vector, float* p_lSpeed,
                                float* p_rSpeed);
    virtual void setTankOutput(float lfSpeed, float lbSpeed,
                               float rfSpeed, float rbSpeed);
    void setTractionControlState(bool enabled);
protected:
    WsDashboard* ap_dashboard;
    WsTractionWheel* ap_scLF;
    WsTractionWheel* ap_scLB;
    WsTractionWheel* ap_scRF;
    WsTractionWheel* ap_scRB;
};

#endif  //_WSDRIVEBASETANK_H
