//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveBaseCrabDual.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEBASECRABDUAL_H)
#define _WSDRIVEBASECRABDUAL_H

#include <stdio.h>
#include "WsDriveBaseTank.h"

class WsDriveBaseCrabDual : public WsDriveBaseTank
{
};

#endif  //_WSDRIVEBASECRABDUAL_H
