//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveVector.cpp
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#include "WsDriveVector.h"

WsDriveVector::WsDriveVector(float speed, float direction)
{
    a_speed = speed;
    a_direction = direction;
}

WsDriveVector::~WsDriveVector()
{
}
