//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveBaseCrabFrontBack.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEBASECRABFRONTBACK_H)
#define _WSDRIVEBASECRABFRONTBACK_H

#include <stdio.h>
#include "WsDriveBaseCrabDual.h"

class WsDriveBaseCrabFrontBack : public WsDriveBaseCrabDual
{
};

#endif  //_WSDRIVEBASECRABFRONTBACK_H
