//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveVector.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEVECTOR_H)
#define _WSDRIVEVECTOR_H

#include <stdio.h>

class WsDriveVector
{
public:
    float a_speed;
    float a_direction;
    WsDriveVector(float speed = 0, float direction = 0);
    virtual ~WsDriveVector();
};

#endif  //_WSDRIVEVECTOR_H
