//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveBaseCrabLeftRight.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEBASECRABLEFTRIGHT_H)
#define _WSDRIVEBASECRABLEFTRIGHT_H

#include <stdio.h>
#include "WsDriveBaseCrabDual.h"

class WsDriveBaseCrabLeftRight : public WsDriveBaseCrabDual
{
};

#endif  //_WSDRIVEBASECRABLEFTRIGHT_H
