//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsEncoder.h
//  @ Date : 2/13/2009
//  @ Author : 
//
//


#if !defined(_WSENCODER_H)
#define _WSENCODER_H

#include <stdio.h>

class WsEncoder {
public:
    WsEncoder(UINT8 addr);
    virtual ~WsEncoder();
    virtual bool isValid(void );
    UINT8 getAddress(void );
    virtual INT16 getDrivenWheelSpeed(void );
    virtual INT16 getIdlerWheelSpeed(void );
    virtual INT16 getSpeedDiff(void );
    virtual INT16 getSlipRatio(void );
protected:
    UINT8 a_addr;
    bool a_validEncoder;
};

#endif  //_WSENCODER_H
