//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsEncoder.cpp
//  @ Date : 2/13/2009
//  @ Author : 
//
//


#include "WsEncoder.h"

WsEncoder::WsEncoder(UINT8 addr)
{
    a_addr = addr;
    a_validEncoder = false;
}

WsEncoder::~WsEncoder()
{

}

bool WsEncoder::isValid(void )
{
    return a_validEncoder;
}

UINT8 WsEncoder::getAddress(void )
{
    return a_addr;
}

INT16 WsEncoder::getDrivenWheelSpeed(void )
{
    return 0;
}

INT16 WsEncoder::getIdlerWheelSpeed(void )
{
    return 0;
}

INT16 WsEncoder::getSpeedDiff(void )
{
    return 0;
}

INT16 WsEncoder::getSlipRatio(void )
{
    return 0;
}

