//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsEncoderManager.h
//  @ Date : 2/5/2009
//  @ Author : 
//
//


#if !defined(_WSENCODERMANAGER_H)
#define _WSENCODERMANAGER_H

#include <stdio.h>

class WsEncoder;
class WsShmEncoder;
class WsCalibration;

class WsEncoderManager
{
public:
    typedef enum
    {
        FRONT_LEFT,
        FRONT_RIGHT,
        BACK_LEFT,
        BACK_RIGHT,
        MAX_WHEEL,
    } WsWheelPosT;

    WsEncoderManager();
    ~WsEncoderManager();
    WsEncoder* getEncoder(WsWheelPosT encoder);
    void discoverStart(void );
    bool discoverEncoder(WsWheelPosT wheel);
    void discoverDone(bool successful);

protected:
    static const UINT8 kMaxNumEncoders = 8;

    WsShmEncoder* ap_encoderArray[kMaxNumEncoders + 1];
    UINT8 a_encoderLoopCountArray[kMaxNumEncoders + 1];

    WsCalibration *ap_calib;
};

#endif  //_WSENCODERMANAGER_H
