//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsEscalatorSide.cpp
//  @ Date : 1/29/2009
//  @ Author : 
//
//


#include "WsEscalatorSide.h"
#include "WsSc.h"

WsEscalatorSide::WsEscalatorSide(WsSc* p_sc)
{
    ap_sc = p_sc;
}

WsEscalatorSide::~WsEscalatorSide()
{

}

void WsEscalatorSide::setSpeed(float speed)
{
    if(ap_sc != NULL)
    {
        ap_sc->Set(speed);
    }
}

