//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsEscalator.h
//  @ Date : 1/29/2009
//  @ Author : 
//
//


#if !defined(_WSESCALATOR_H)
#define _WSESCALATOR_H

#include <stdio.h>

class WsSc;
class WsEscalatorSide;
class WsDashboard;

class WsEscalator
{
public:
    WsEscalator(WsSc* p_frontSc, WsSc* p_backSc);
    ~WsEscalator();
    void setSpeed(float frontSpeed, float backSpeed, float* frontSpeedOut, float* backSpeedOut);

    static const float a_escOff = 0;
    static const float a_escFullUp = 1;
    static const float a_escFullDown = -1;

protected:
    WsEscalatorSide* ap_front;
    WsEscalatorSide* ap_back;
    WsDashboard* ap_dashboard;
};

#endif  //_WSESCALATOR_H
