//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsEscalatorSide.h
//  @ Date : 1/29/2009
//  @ Author : 
//
//


#if !defined(_WSESCALATORSIDE_H)
#define _WSESCALATORSIDE_H

#include <stdio.h>

class WsSc;

class WsEscalatorSide
{
public:
    WsEscalatorSide(WsSc* p_sc);
    ~WsEscalatorSide();
    void setSpeed(float speed);
protected:
    WsSc* ap_sc;
};

#endif  //_WSESCALATORSIDE_H
