//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsEscalator.cpp
//  @ Date : 1/29/2009
//  @ Author : 
//
//


#include "WsEscalator.h"
#include "WsEscalatorSide.h"
#include "WsSc.h"
#include "WsDashboard.h"

WsEscalator::WsEscalator(WsSc* p_frontSc, WsSc* p_backSc)
{
    ap_front = new WsEscalatorSide(p_frontSc);
    ap_back = new WsEscalatorSide(p_backSc);
    ap_dashboard = WsDashboard::getInstance();
}

WsEscalator::~WsEscalator()
{
    delete ap_front;
    ap_front = NULL;

    delete ap_back;
    ap_back = NULL;
}

void WsEscalator::setSpeed(float frontSpeed, float backSpeed, float* frontSpeedOut, float* backSpeedOut)
{
    if(ap_front != NULL)
    {
        ap_front->setSpeed(frontSpeed);
        *frontSpeedOut = frontSpeed;
    }
    else
    {
        *frontSpeedOut = 0;
    }

    if(ap_back != NULL)
    {
        ap_back->setSpeed(backSpeed);
        *backSpeedOut = backSpeed;
    }
    else
    {
        *backSpeedOut = 0;
    }
    ap_dashboard->setValue(IDX_OUT_ESC_FRONT, frontSpeed);
    ap_dashboard->setValue(IDX_OUT_ESC_BACK, backSpeed);

}

