//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsFlightStickJoystick.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSFLIGHTSTICKJOYSTICK_H)
#define _WSFLIGHTSTICKJOYSTICK_H

#include <stdio.h>
#include "WsRegularJoystick.h"

class WsFlightStickJoystick : public WsRegularJoystick
{
};

#endif  //_WSFLIGHTSTICKJOYSTICK_H
