//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsGamepadJoystick.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSGAMEPADJOYSTICK_H)
#define _WSGAMEPADJOYSTICK_H

#include <stdio.h>
#include "Joystick.h"

class WsGamepadJoystick : public Joystick
{
};

#endif  //_WSGAMEPADJOYSTICK_H
