//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsPs2Joystick.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSPS2JOYSTICK_H)
#define _WSPS2JOYSTICK_H

#include <stdio.h>
#include "WsGamepadJoystick.h"

class WsPs2Joystick : public WsGamepadJoystick
{
};

#endif  //_WSPS2JOYSTICK_H
