//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsRelay.cpp
//  @ Date : 1/24/2009
//  @ Author : 
//
//


#include "WsRelay.h"
#include "WsOutput.h"
#include "Relay.h"

WsRelay::WsRelay(Relay* p_relay)
{
    ap_relay = p_relay;

}

WsRelay::~WsRelay()
{

}

void WsRelay::Set(Relay::Value value)
{
    if(a_enabled == true)
    {
        ap_relay->Set(value);
    }
    else
    {
        ap_relay->Set(Relay::kOff);
    }

}

