//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsRegularJoystick.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSREGULARJOYSTICK_H)
#define _WSREGULARJOYSTICK_H

#include <stdio.h>
#include "Joystick.h"

class WsRegularJoystick : public Joystick
{
};

#endif  //_WSREGULARJOYSTICK_H
