//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsSc.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSSC_H)
#define _WSSC_H

#include <stdio.h>
#include "WsOutput.h"

class SpeedController;
class WsDashboard;

class WsSc : public WsOutput
{
public:
    WsSc(SpeedController* p_sc);
    virtual ~WsSc();
    virtual float Get(void);
    virtual void Set(float speed);
    bool a_debug;
protected:
    SpeedController *ap_sc;
    WsDashboard* ap_dashboard;
};

#endif  //_WSSC_H
