//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsShmEncoder.h
//  @ Date : 2/13/2009
//  @ Author : 
//
//


#if !defined(_WSSHMENCODER_H)
#define _WSSHMENCODER_H

#include <stdio.h>
#include "SensorBase.h"
#include "WsEncoder.h"

class WsShmEncoder : public WsEncoder {
public:
    WsShmEncoder(UINT8 addr, bool invert);
    virtual ~WsShmEncoder();
    INT16 getShmValue(void );
    virtual bool isValid(void );
    virtual INT16 getDrivenWheelSpeed(void );
    virtual INT16 getIdlerWheelSpeed(void );
    virtual INT16 getSpeedDiff(void );
    virtual INT16 getSlipRatio(void );
protected:
    static const int kTimeout = SensorBase::kSystemClockTicksPerMicrosecond * 1000 * 15;
    bool a_invert;
};

#endif  //_WSSHMENCODER_H
