//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsShooter.cpp
//  @ Date : 1/29/2009
//  @ Author : 
//
//


#include "WsShooter.h"
#include "WsSc.h"
#include "WsDashboard.h"

WsShooter::WsShooter(WsSc* p_sc)
{
    ap_sc = p_sc;
    a_shooterSpeedIn = 1;
    a_shooterSpeedOut = -1;
    //a_shooterSpeedOutSlow = -.7;
    a_shooterSpeedOutSlow = -.35;

    ap_dashboard = WsDashboard::getInstance();
}

float WsShooter::setState(WsShooterStateT state)
{
    float speed = 0;
    switch(state)
    {
        case SHOOTER_STATE_OFF:
            speed = 0;
            break;
        case SHOOTER_STATE_IN:
            speed = a_shooterSpeedIn;
            break;
        case SHOOTER_STATE_OUT_FAST:
            speed = a_shooterSpeedOut;
            break;
        case SHOOTER_STATE_OUT_SLOW:
            speed = a_shooterSpeedOutSlow;
            break;
        default:
            speed = 0;
            break;
    }

    if(ap_sc != NULL)
    {
        ap_sc->Set(speed);
    }
    ap_dashboard->setValue(IDX_OUT_SHOOTER, speed);
    return speed;
}


