//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsTankControlMethod.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSTANKCONTROLMETHOD_H)
#define _WSTANKCONTROLMETHOD_H

#include <stdio.h>
#include "WsControlMethodBase.h"

class WsTankControlMethod : public WsControlMethodBase
{
};

#endif  //_WSTANKCONTROLMETHOD_H
