//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsTractionWheel.h
//  @ Date : 2/7/2009
//  @ Author : 
//
//


#if !defined(_WSTRACTIONWHEEL_H)
#define _WSTRACTIONWHEEL_H

#include <stdio.h>
#include "WsSc.h"

class WsEncoder;
class WsPid;

class WsTractionWheel : public WsSc
{
public:
    typedef enum
    {
        WHEEL_FL,
        WHEEL_FR,
        WHEEL_BL,
        WHEEL_BR,
    } WheelIndexT;

    WsTractionWheel(SpeedController* p_sc, WsEncoder* p_encoder, WheelIndexT wheel);
    ~WsTractionWheel();
    virtual void Set(float inSpeed);
    virtual float Get(void);
    void SetTractionControlState(bool state);
    INT16 GetDrivenWheelSpeed(void);
    INT16 GetIdlerWheelSpeed(void);
    INT16 GetSlipRatio(void);
    float GetDesOutputSpeed(void);
    float GetActOutputSpeed(void);
    bool ReadEncoders(void);

protected:
    WsEncoder* ap_encoder;
    WheelIndexT a_wheel;
    WsPid* ap_tractionPID;
    bool a_tractionControlEnabled;
    float a_lastSpeed;

    INT16 a_drivenWheelSpeed;
    INT16 a_idlerWheelSpeed;
    INT16 a_slipRatio;
    float a_desOutputSpeed;
    float a_actOutputSpeed;
};

#endif  //_WSTRACTIONWHEEL_H
