//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerAxis.h
//  @ Date : 1/8/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERAXIS_H)
#define _WSCONTROLLERAXIS_H

#include "WsControllerBase.h"

class WsControllerAxis : public WsControllerBase
{
public:
	WsControllerAxis(Joystick* p_js, UINT32 axis);
	float getValue();
protected:
	UINT32 a_axisNum;
};

#endif  //_WSCONTROLLERAXIS_H
