//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerStickyButton.cpp
//  @ Date : 1/8/2009
//  @ Author : 
//
//


#include <stdio.h>
#include "WsControllerButton.h"
#include "WsControllerStickyButton.h"

WsControllerStickyButton::WsControllerStickyButton(Joystick* p_js, UINT32 button) :
    WsControllerButton(p_js, button)
{
    a_stickyState = false;
    a_statePrev = false;
}


bool WsControllerStickyButton::getState(void) 
{
    bool rawState;
    
    rawState = WsControllerButton::getState();
    
    if((rawState == true) && (a_statePrev == false))
    {
        a_stickyState = !a_stickyState;
    }
    
    //printf("Prev: %d  Cur: %d Out: %d\n", a_statePrev, rawState, a_stickyState);
    a_statePrev = rawState;
    return a_stickyState;
}
