//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerStickyButton.h
//  @ Date : 1/8/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERSTICKYBUTTON_H)
#define _WSCONTROLLERSTICKYBUTTON_H

class WsControllerButton;

class WsControllerStickyButton : public WsControllerButton 
{
public:
	WsControllerStickyButton(Joystick* p_js, UINT32 button);
	virtual bool getState(void);
protected:
	bool a_stickyState;
	bool a_statePrev;
};

#endif  //_WSCONTROLLERSTICKYBUTTON_H
