//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerBase.h
//  @ Date : 1/7/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERBASE_H)
#define _WSCONTROLLERBASE_H

#include "Joystick.h"

class WsControllerBase {
protected:
	Joystick *ap_joystick;
};

#endif  //_WSCONTROLLERBASE_H
