//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerButton.h
//  @ Date : 1/7/2009
//  @ Author : 
//
//

#if !defined(_WSCONTROLLERBUTTON_H)
#define _WSCONTROLLERBUTTON_H

#include "WsControllerBase.h"

class WsControllerButton : public WsControllerBase {
public:
	WsControllerButton(Joystick* p_js, UINT32 button);
	virtual bool getState(void);
protected:
	UINT32 a_buttonNum;
};

#endif  //_WSCONTROLLERBUTTON_H
