//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerAxis.cpp
//  @ Date : 1/8/2009
//  @ Author : 
//
//


#include "WsControllerBase.h"
#include "WsControllerAxis.h"

WsControllerAxis::WsControllerAxis(Joystick* p_js, UINT32 axis)
{
    ap_joystick = p_js;
	a_axisNum = axis;

}

float WsControllerAxis::getValue()
{
    return ap_joystick->GetRawAxis(a_axisNum);
}

