//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControllerButton.cpp
//  @ Date : 1/7/2009
//  @ Author : 
//
//

#include "WsControllerButton.h"

WsControllerButton::WsControllerButton(Joystick* p_js, UINT32 button)
{
	ap_joystick = p_js;
	a_buttonNum = button;
}

bool WsControllerButton::getState(void)
{
	return ap_joystick->GetRawButton(a_buttonNum);
}

